project:
  type: website

website:
  title: "User Interfaces"
  image: "logo.svg"
  favicon: "favicon.png"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: |
      &copy; Michael Haaf, 2023-24
    center:
      - text: "About"
        href: about/index.qmd
    right:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS      
  sidebar:
    logo: logo.svg
    style: "docked"
    align: center
    tools: 
      - icon: person-fill
        text: "Omnivox"
        menu:
          - text: Discussion forum
            url: http://example.org
          - text: Announcements
            url: http://example.org
          - text: Gradebook
            url: http://example.org
      - icon: github
        href: https://github.com/420-2W6/W24
        text: "Course source code"
    search: true
    contents: auto

format:
  html:
    css: styles.css
    number-sections: true
    toc: true
    code-copy: true
    code-overflow: wrap
    theme:
      light: [journal, theme.scss]
      dark: [journal, theme-dark.scss]
